"""Pydantic models for OpenAI-compatible API."""

from __future__ import annotations

import time
import uuid
from typing import Any, Literal

from pydantic import BaseModel, Field


# ==================== Tool Use / Function Calling Models ====================

class FunctionDefinition(BaseModel):
    """Function definition for tool use."""

    name: str = Field(..., description="The name of the function")
    description: str = Field(..., description="A description of what the function does")
    parameters: dict[str, Any] = Field(
        default_factory=dict,
        description="The parameters the function accepts, as a JSON Schema object",
    )


class ToolFunction(BaseModel):
    """Wrapper for function definition in tools."""

    type: Literal["function"] = "function"
    function: FunctionDefinition


class ToolCallFunction(BaseModel):
    """Function call details in assistant message."""

    name: str = Field(..., description="The name of the function to call")
    arguments: str = Field(
        ..., description="The arguments to call the function with, as a JSON string"
    )


class ToolCall(BaseModel):
    """Tool call in assistant message."""

    id: str = Field(default_factory=lambda: f"call_{uuid.uuid4().hex[:24]}")
    type: Literal["function"] = "function"
    function: ToolCallFunction


# ==================== Message Models ====================

class ChatMessage(BaseModel):
    """A chat message in the conversation."""

    role: Literal["system", "user", "assistant", "tool"] = Field(
        ..., description="The role of the message author"
    )
    content: str | None = Field(
        default=None, description="The content of the message"
    )
    name: str | None = Field(
        default=None, description="The name of the author (for tool messages)"
    )
    tool_calls: list[ToolCall] | None = Field(
        default=None, description="Tool calls generated by the model"
    )
    tool_call_id: str | None = Field(
        default=None, description="The ID of the tool call (for tool messages)"
    )


# ==================== Request Models ====================

class ResponseFormat(BaseModel):
    """Response format specification."""

    type: Literal["text", "json_object", "json_schema"] = Field(
        default="text", description="The format of the response"
    )
    json_schema: dict[str, Any] | None = Field(
        default=None, description="The JSON schema for structured output"
    )


class ChatCompletionRequest(BaseModel):
    """Request body for chat completion endpoint."""

    model: str = Field(
        default="llama3.1-8B", description="ID of the model to use"
    )
    messages: list[ChatMessage] = Field(
        ..., description="A list of messages comprising the conversation"
    )
    stream: bool = Field(
        default=False, description="Whether to stream back partial progress"
    )
    temperature: float | None = Field(
        default=None, ge=0, le=2, description="Sampling temperature (mapped to top_k)"
    )
    top_p: float | None = Field(
        default=None, ge=0, le=1, description="Nucleus sampling parameter"
    )
    top_k: int | None = Field(
        default=8, ge=1, description="Top-K sampling parameter"
    )
    max_tokens: int | None = Field(
        default=None, ge=1, description="Maximum number of tokens to generate"
    )
    stop: str | list[str] | None = Field(
        default=None, description="Stop sequences"
    )
    tools: list[ToolFunction] | None = Field(
        default=None, description="A list of tools the model may call"
    )
    tool_choice: Literal["none", "auto", "required"] | dict | None = Field(
        default="auto", description="Controls tool calling behavior"
    )
    response_format: ResponseFormat | None = Field(
        default=None, description="Format specification for the response"
    )
    user: str | None = Field(
        default=None, description="A unique identifier for the end-user"
    )

    def get_system_prompt(self) -> str:
        """Extract system prompt from messages or return empty string."""
        for msg in self.messages:
            if msg.role == "system":
                return msg.content or ""
        return ""

    def get_chat_messages(self) -> list[dict]:
        """Get non-system messages for the chat API."""
        return [
            {"role": msg.role, "content": msg.content or ""}
            for msg in self.messages
            if msg.role != "system"
        ]

    def build_enhanced_system_prompt(self) -> str:
        """Build system prompt with tool and JSON schema instructions."""
        base_prompt = self.get_system_prompt()
        parts = [base_prompt] if base_prompt else []

        # Add tool instructions if tools are provided
        if self.tools:
            tool_instructions = self._build_tool_instructions()
            parts.append(tool_instructions)

        # Add JSON schema instructions if response_format is provided
        if self.response_format and self.response_format.type != "text":
            json_instructions = self._build_json_instructions()
            parts.append(json_instructions)

        return "\n\n".join(parts)

    def _build_tool_instructions(self) -> str:
        """Build tool instructions for prompt engineering."""
        lines = ["You have access to the following tools:"]

        for tool in self.tools or []:
            func = tool.function
            lines.append(f"\n## {func.name}")
            lines.append(f"Description: {func.description}")
            if func.parameters:
                lines.append(f"Parameters: {func.parameters}")

        lines.append("\nWhen you need to call a tool, respond in this JSON format:")
        lines.append('{"tool": "tool_name", "arguments": {...}}')

        if self.tool_choice == "none":
            lines.append("\nDo not use any tools. Respond directly.")
        elif self.tool_choice == "required":
            lines.append("\nYou MUST use a tool to answer.")
        else:
            lines.append("\nUse a tool only if it helps answer the user's question.")

        return "\n".join(lines)

    def _build_json_instructions(self) -> str:
        """Build JSON format instructions for prompt engineering."""
        lines = ["You must respond in valid JSON format."]

        if self.response_format and self.response_format.json_schema:
            lines.append("\nFollow this JSON schema:")
            lines.append(str(self.response_format.json_schema))

        lines.append("\nDo not include any text outside the JSON object.")

        return "\n".join(lines)


# ==================== Response Models ====================

class Usage(BaseModel):
    """Token usage information."""

    prompt_tokens: int = Field(default=0, description="Number of tokens in the prompt")
    completion_tokens: int = Field(
        default=0, description="Number of tokens in the completion"
    )
    total_tokens: int = Field(
        default=0, description="Total number of tokens used"
    )


class ChoiceMessage(BaseModel):
    """Message in a choice."""

    role: Literal["assistant"] = "assistant"
    content: str | None = Field(default=None, description="The message content")
    tool_calls: list[ToolCall] | None = Field(
        default=None, description="Tool calls generated by the model"
    )


class Choice(BaseModel):
    """A completion choice."""

    index: int = Field(..., description="The index of the choice")
    message: ChoiceMessage = Field(..., description="The message content")
    finish_reason: Literal["stop", "length", "tool_calls", "content_filter"] | None = (
        Field(default="stop", description="The reason the completion finished")
    )
    logprobs: dict | None = Field(default=None, description="Log probabilities")


class ChatCompletionResponse(BaseModel):
    """Response from chat completion endpoint."""

    id: str = Field(
        default_factory=lambda: f"chatcmpl-{uuid.uuid4().hex}",
        description="A unique identifier for the completion",
    )
    object: Literal["chat.completion"] = "chat.completion"
    created: int = Field(
        default_factory=lambda: int(time.time()),
        description="The Unix timestamp when the completion was created",
    )
    model: str = Field(..., description="The model used for completion")
    choices: list[Choice] = Field(..., description="A list of completion choices")
    usage: Usage = Field(..., description="Token usage information")
    system_fingerprint: str | None = Field(
        default=None, description="System fingerprint"
    )


class ChoiceDelta(BaseModel):
    """Delta message in streaming response."""

    role: Literal["assistant"] | None = None
    content: str | None = None
    tool_calls: list[ToolCall] | None = None


class StreamingChoice(BaseModel):
    """A choice in a streaming response."""

    index: int = 0
    delta: ChoiceDelta = Field(default_factory=ChoiceDelta)
    finish_reason: Literal["stop", "length", "tool_calls", "content_filter"] | None = (
        None
    )
    logprobs: dict | None = None


class ChatCompletionStreamResponse(BaseModel):
    """Streaming response chunk from chat completion endpoint."""

    id: str = Field(default_factory=lambda: f"chatcmpl-{uuid.uuid4().hex}")
    object: Literal["chat.completion.chunk"] = "chat.completion.chunk"
    created: int = Field(default_factory=lambda: int(time.time()))
    model: str
    choices: list[StreamingChoice]
    system_fingerprint: str | None = None


# ==================== Model Listing Models ====================

class ModelInfo(BaseModel):
    """Information about a model."""

    id: str = Field(..., description="The model identifier")
    object: Literal["model"] = "model"
    created: int = Field(default=0, description="Unix timestamp of model creation")
    owned_by: str = Field(default="Taalas Inc.", description="Organization that owns the model")


class ModelList(BaseModel):
    """List of available models."""

    object: Literal["list"] = "list"
    data: list[ModelInfo]


# ==================== Error Models ====================

class ErrorDetail(BaseModel):
    """Error detail in API response."""

    message: str
    type: str
    param: str | None = None
    code: str | None = None


class ErrorResponse(BaseModel):
    """Error response from API."""

    error: ErrorDetail


# ==================== Health Check Models ====================

class HealthResponse(BaseModel):
    """Health check response."""

    status: str
    healthy: bool
    backend: str | None = None
    timestamp: str | None = None
